"""
models.py
Data structures, enums, and dataclasses for ASTRA Stage 15 — Explainability & Confidence Reasoning Engine.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Any, Union


class AstraStatus(str, Enum):
    """Canonical user-facing status vocabulary for ASTRA."""
    CONFIRMED = "CONFIRMED"
    ESTIMATED = "ESTIMATED"
    POSSIBLE = "POSSIBLE"
    UNKNOWN = "UNKNOWN"


class EvidenceCategory(str, Enum):
    """Standardized evidence domains across Stages 1–14."""
    MODEL_PREDICTION = "MODEL_PREDICTION"
    DSP_MEASUREMENT = "DSP_MEASUREMENT"
    SYNCHRONIZATION = "SYNCHRONIZATION"
    CONSTELLATION = "CONSTELLATION"
    DEMODULATION = "DEMODULATION"
    INTERLEAVER = "INTERLEAVER"
    FEC = "FEC"
    CRC_VALIDATION = "CRC_VALIDATION"
    FRAME_STRUCTURE = "FRAME_STRUCTURE"
    BITSTREAM_STRUCTURE = "BITSTREAM_STRUCTURE"
    PAYLOAD_PARSE = "PAYLOAD_PARSE"
    PIPELINE_SCORE = "PIPELINE_SCORE"
    USER_OVERRIDE = "USER_OVERRIDE"


class EvidenceStrength(str, Enum):
    """Magnitude of evidential support."""
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    NEUTRAL = "NEUTRAL"
    CONTRADICTORY = "CONTRADICTORY"
    UNKNOWN = "UNKNOWN"


class EvidenceDirection(str, Enum):
    """Direction of support toward a hypothesis or claim."""
    SUPPORT = "SUPPORT"
    CONTRADICT = "CONTRADICT"
    NEUTRAL = "NEUTRAL"


class IndependenceGroup(str, Enum):
    """Groups of correlated evidence to prevent double-counting in confidence scoring."""
    MODULATION_MODELS = "MODULATION_MODELS"
    DSP_SIGNAL_STRUCTURE = "DSP_SIGNAL_STRUCTURE"
    SYNC = "SYNC"
    CONSTELLATION = "CONSTELLATION"
    DEMODULATION = "DEMODULATION"
    FEC_INTERNAL = "FEC_INTERNAL"
    CRC = "CRC"
    FRAME_PERIODICITY = "FRAME_PERIODICITY"
    HEADER_STRUCTURE = "HEADER_STRUCTURE"
    PAYLOAD_STRUCTURE = "PAYLOAD_STRUCTURE"
    PIPELINE_RANKING = "PIPELINE_RANKING"
    USER_OVERRIDE = "USER_OVERRIDE"


class ContradictionSeverity(str, Enum):
    """Severity classification for pipeline contradictions."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class NodeType(str, Enum):
    """Reasoning graph node categories."""
    CLAIM = "CLAIM"
    EVIDENCE = "EVIDENCE"
    STAGE = "STAGE"
    CONTRADICTION = "CONTRADICTION"


class EdgeType(str, Enum):
    """Reasoning graph relationship categories."""
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    DEPENDS_ON = "DEPENDS_ON"
    DERIVED_FROM = "DERIVED_FROM"


@dataclass
class EvidenceItem:
    """Atomic evidence record generated by upstream stages."""
    evidence_id: str
    stage: str
    category: EvidenceCategory
    description: str
    value: Any = None
    normalized_score: float = 1.0
    strength: EvidenceStrength = EvidenceStrength.MODERATE
    direction: EvidenceDirection = EvidenceDirection.SUPPORT
    independence_group: IndependenceGroup = IndependenceGroup.DSP_SIGNAL_STRUCTURE
    source_reference: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "evidence_id": self.evidence_id,
            "stage": self.stage,
            "category": self.category.value,
            "description": self.description,
            "value": str(self.value) if self.value is not None else None,
            "normalized_score": round(float(self.normalized_score), 4),
            "strength": self.strength.value,
            "direction": self.direction.value,
            "independence_group": self.independence_group.value,
            "source_reference": self.source_reference
        }


@dataclass
class EvidenceGroup:
    """Aggregated evidence under a common independence domain."""
    group_id: IndependenceGroup
    items: List[EvidenceItem] = field(default_factory=list)
    has_strong_evidence: bool = False
    mean_score: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "group_id": self.group_id.value,
            "item_count": len(self.items),
            "has_strong_evidence": self.has_strong_evidence,
            "mean_score": round(float(self.mean_score), 4),
            "items": [it.to_dict() for it in self.items]
        }


@dataclass
class Contradiction:
    """Documented inconsistency or clash between two evidence sources."""
    contradiction_id: str
    fields_involved: List[str]
    evidence_a: str
    evidence_b: str
    severity: ContradictionSeverity
    description: str
    resolution_status: str = "UNRESOLVED"  # RESOLVED_BY_DOWNSTREAM, UNRESOLVED, OVERRIDDEN
    penalty: float = 0.0

    def __post_init__(self):
        if self.resolution_status is False:
            self.resolution_status = "UNRESOLVED"
        elif self.resolution_status is True:
            self.resolution_status = "RESOLVED_BY_DOWNSTREAM"

        if self.penalty == 0.0 and self.resolution_status != "RESOLVED_BY_DOWNSTREAM":
            pen_map = {
                ContradictionSeverity.LOW: 0.02,
                ContradictionSeverity.MEDIUM: 0.06,
                ContradictionSeverity.HIGH: 0.15,
                ContradictionSeverity.CRITICAL: 0.30,
            }
            self.penalty = pen_map.get(self.severity, 0.05)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "contradiction_id": self.contradiction_id,
            "fields_involved": self.fields_involved,
            "evidence_a": self.evidence_a,
            "evidence_b": self.evidence_b,
            "severity": self.severity.value,
            "description": self.description,
            "resolution_status": self.resolution_status,
            "penalty": round(float(self.penalty), 4)
        }


@dataclass
class MissingEvidence:
    """Expected evidence that was not present in the capture or analysis."""
    missing_id: str
    category: EvidenceCategory
    field_name: str
    impact_description: str
    evidence_type: str = ""
    severity: str = "LOW"
    penalty: float = 0.0

    def __post_init__(self):
        if not self.evidence_type:
            if self.category == EvidenceCategory.CRC_VALIDATION:
                self.evidence_type = "CRC Validation"
            elif self.field_name == "protocol":
                self.evidence_type = "Protocol Profile"
            else:
                self.evidence_type = self.category.value.replace("_", " ").title()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "missing_id": self.missing_id,
            "category": self.category.value,
            "field_name": self.field_name,
            "impact_description": self.impact_description,
            "severity": self.severity,
            "penalty": round(float(self.penalty), 4)
        }


@dataclass
class FieldExplanation:
    """Detailed justification and confidence audit for an individual field."""
    field_name: str
    value: Any
    status: AstraStatus
    confidence_score: float
    confidence_type: str = "ASTRA Reasoning Confidence"  # "ASTRA Reasoning Confidence" or "Calibrated Probability"
    status_reason: str = ""
    supporting_evidence: List[str] = field(default_factory=list)
    contradicting_evidence: List[str] = field(default_factory=list)
    missing_evidence: List[str] = field(default_factory=list)
    alternatives: List[Dict[str, Any]] = field(default_factory=list)
    source_stages: List[str] = field(default_factory=list)
    reasoning_text: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "field_name": self.field_name,
            "value": str(self.value) if self.value is not None else None,
            "status": self.status.value,
            "confidence_score": round(float(self.confidence_score), 4),
            "confidence_type": self.confidence_type,
            "status_reason": self.status_reason,
            "supporting_evidence": self.supporting_evidence,
            "contradicting_evidence": self.contradicting_evidence,
            "missing_evidence": self.missing_evidence,
            "alternatives": self.alternatives,
            "source_stages": self.source_stages,
            "reasoning_text": self.reasoning_text
        }


class CandidateExplanation:
    """Comparative analysis for an individual candidate pipeline."""
    pipeline_id: str
    rank: int
    score: float
    status: AstraStatus
    margin_to_next: float
    key_strengths: List[str]
    key_weaknesses: List[str]
    why_lost: Optional[str]
    field_values: Dict[str, Any]

    def __init__(
        self,
        pipeline_id: str,
        rank: int = 1,
        score: float = 0.0,
        status: Any = AstraStatus.CONFIRMED,
        margin_to_next: Any = 0.0,
        key_strengths: Any = None,
        key_weaknesses: Any = None,
        why_lost: Any = None,
        field_values: Any = None,
        **kwargs
    ):
        self.pipeline_id = str(pipeline_id)
        self.rank = int(rank)
        self.score = float(score)

        # Handle legacy positional calls: (pipeline_id, rank, score, val_score, mod, baud, intl, fec, is_best)
        if isinstance(margin_to_next, str) or isinstance(status, (int, float)):
            # Legacy signature
            st_val = AstraStatus.CONFIRMED if self.score >= 0.85 else AstraStatus.ESTIMATED
            self.status = st_val
            self.margin_to_next = 0.35
            self.key_strengths = []
            self.key_weaknesses = []
            self.why_lost = None
            self.field_values = {
                "modulation": str(margin_to_next),
                "symbol_rate": float(key_strengths) if isinstance(key_strengths, (int, float)) else key_strengths,
                "interleaver": key_weaknesses,
                "fec": why_lost
            }
        else:
            if isinstance(status, str):
                try:
                    self.status = AstraStatus(status)
                except ValueError:
                    self.status = AstraStatus.CONFIRMED
            else:
                self.status = status or AstraStatus.CONFIRMED
            self.margin_to_next = float(margin_to_next) if margin_to_next is not None else 0.0
            self.key_strengths = list(key_strengths) if isinstance(key_strengths, (list, tuple)) else []
            self.key_weaknesses = list(key_weaknesses) if isinstance(key_weaknesses, (list, tuple)) else []
            self.why_lost = str(why_lost) if why_lost is not None else None
            self.field_values = dict(field_values) if isinstance(field_values, dict) else {}

    @property
    def is_best(self) -> bool:
        return self.rank in (0, 1)

    @property
    def modulation(self) -> Any:
        return self.field_values.get("modulation")

    @property
    def symbol_rate(self) -> Any:
        return self.field_values.get("symbol_rate")

    @property
    def fec_scheme(self) -> Any:
        return self.field_values.get("fec") or self.field_values.get("fec_scheme")

    @property
    def interleaver(self) -> Any:
        return self.field_values.get("interleaver")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "pipeline_id": self.pipeline_id,
            "rank": self.rank,
            "score": round(float(self.score), 4),
            "status": self.status.value,
            "margin_to_next": round(float(self.margin_to_next), 4),
            "key_strengths": self.key_strengths,
            "key_weaknesses": self.key_weaknesses,
            "why_lost": self.why_lost,
            "field_values": self.field_values
        }


@dataclass
class ConfidenceBreakdown:
    """Component-by-component decomposition of final confidence."""
    overall_score: float = 0.0
    calibrated_probability: Optional[float] = None
    modulation_confidence: float = 0.0
    symbol_rate_confidence: float = 0.0
    synchronization_confidence: float = 0.0
    demodulation_confidence: float = 0.0
    interleaver_confidence: float = 0.0
    fec_confidence: float = 0.0
    validation_confidence: float = 0.0
    structure_confidence: float = 0.0
    payload_confidence: float = 0.0
    contradiction_penalty: float = 0.0
    margin_adjustment: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "overall_score": round(float(self.overall_score), 4),
            "calibrated_probability": round(float(self.calibrated_probability), 4) if self.calibrated_probability is not None else None,
            "components": {
                "modulation": round(float(self.modulation_confidence), 4),
                "symbol_rate": round(float(self.symbol_rate_confidence), 4),
                "synchronization": round(float(self.synchronization_confidence), 4),
                "demodulation": round(float(self.demodulation_confidence), 4),
                "interleaver": round(float(self.interleaver_confidence), 4),
                "fec": round(float(self.fec_confidence), 4),
                "validation": round(float(self.validation_confidence), 4),
                "structure": round(float(self.structure_confidence), 4),
                "payload": round(float(self.payload_confidence), 4),
            },
            "penalties_and_adjustments": {
                "contradiction_penalty": round(float(self.contradiction_penalty), 4),
                "margin_adjustment": round(float(self.margin_adjustment), 4)
            }
        }


@dataclass
class ReasoningNode:
    """Graph node representing an individual claim, stage, or evidence item."""
    node_id: str
    node_type: NodeType
    label: str
    details: str = ""
    stage: str = ""
    status: Optional[AstraStatus] = None
    confidence_score: Optional[float] = None
    properties: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "node_id": self.node_id,
            "node_type": self.node_type.value,
            "label": self.label,
            "details": self.details,
            "stage": self.stage,
            "status": self.status.value if self.status else None,
            "confidence_score": round(float(self.confidence_score), 4) if self.confidence_score is not None else None,
            "properties": self.properties
        }


@dataclass
class ReasoningEdge:
    """Directed edge linking reasoning nodes in the explanation graph."""
    source_id: str
    target_id: str
    edge_type: EdgeType
    weight: float = 1.0
    description: str = ""
    label: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "source_id": self.source_id,
            "target_id": self.target_id,
            "edge_type": self.edge_type.value,
            "weight": round(float(self.weight), 4),
            "description": self.description or self.label,
            "label": self.label or self.description
        }


@dataclass
class ReasoningGraph:
    """Machine-readable directed graph of evidence, stages, and claims."""
    nodes: List[ReasoningNode] = field(default_factory=list)
    edges: List[ReasoningEdge] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "node_count": len(self.nodes),
            "edge_count": len(self.edges),
            "nodes": [n.to_dict() for n in self.nodes],
            "edges": [e.to_dict() for e in self.edges]
        }


@dataclass
class GuiCard:
    """Compact summary card tailored for GUI badges and dashboard views."""
    field_name: str
    value_str: str = ""
    status: AstraStatus = AstraStatus.UNKNOWN
    confidence_pct: int = 0
    badge_color: str = "gray"  # green, cyan, amber, gray
    title: str = ""
    value_display: str = ""
    confidence_display: str = ""
    subtitle: str = ""

    def __post_init__(self):
        if not self.value_str and self.value_display:
            self.value_str = self.value_display
        if not self.value_display and self.value_str:
            self.value_display = self.value_str
        if not self.title:
            self.title = self.field_name.replace("_", " ").title()
        if not self.confidence_display and self.confidence_pct:
            self.confidence_display = f"{self.confidence_pct}%"

    @property
    def primary_value(self) -> str:
        return self.value_display or self.value_str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "field_name": self.field_name,
            "title": self.title,
            "value_display": self.value_display or self.value_str,
            "status": self.status.value,
            "confidence_display": self.confidence_display,
            "confidence_pct": self.confidence_pct,
            "badge_color": self.badge_color,
            "subtitle": self.subtitle
        }


@dataclass
class GuiSummary:
    """Ready-to-render data structures for Stage 16 GUI."""
    overall_status: AstraStatus = AstraStatus.UNKNOWN
    overall_confidence_badge: str = ""
    cards: List[GuiCard] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    timeline_items: List[str] = field(default_factory=list)
    reasoning_timeline: List[Dict[str, str]] = field(default_factory=list)
    key_strengths: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "overall_status": self.overall_status.value,
            "overall_confidence_badge": self.overall_confidence_badge,
            "cards": [c.to_dict() for c in self.cards],
            "warnings": self.warnings,
            "timeline_items": self.timeline_items,
            "reasoning_timeline": self.reasoning_timeline,
            "key_strengths": self.key_strengths
        }


@dataclass
class ExplainabilityResult:
    """
    Comprehensive output of ASTRA Stage 15 Explainability & Confidence Reasoning Engine.
    Exposes auditable decision rationales, confidence decomposition, candidate comparisons,
    and machine-readable graphs.
    """
    signal_id: str
    best_pipeline_id: str
    overall_status: AstraStatus
    overall_confidence: float
    calibrated_probability: Optional[float] = None

    field_explanations: Dict[str, FieldExplanation] = field(default_factory=dict)
    candidate_comparison: List[CandidateExplanation] = field(default_factory=list)
    evidence_summary: List[EvidenceItem] = field(default_factory=list)
    contradictions: List[Contradiction] = field(default_factory=list)
    missing_evidence: List[MissingEvidence] = field(default_factory=list)
    uncertainty_sources: List[str] = field(default_factory=list)
    alternative_hypotheses: List[Dict[str, Any]] = field(default_factory=list)

    confidence_breakdown: Optional[ConfidenceBreakdown] = None
    reasoning_graph: Optional[ReasoningGraph] = None
    reasoning_trace: List[str] = field(default_factory=list)

    human_summary: str = ""
    technical_summary: str = ""
    gui_summary: Optional[GuiSummary] = None

    model_versions: Dict[str, str] = field(default_factory=dict)
    processing_versions: Dict[str, str] = field(default_factory=dict)
    processing_provenance: Dict[str, Any] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "best_pipeline_id": self.best_pipeline_id,
            "overall_status": self.overall_status.value,
            "overall_confidence": round(float(self.overall_confidence), 4),
            "calibrated_probability": round(float(self.calibrated_probability), 4) if self.calibrated_probability is not None else None,
            "fields": {k: v.to_dict() for k, v in self.field_explanations.items()},
            "confidence_breakdown": self.confidence_breakdown.to_dict() if self.confidence_breakdown else None,
            "candidate_comparison": [c.to_dict() for c in self.candidate_comparison],
            "evidence_summary_count": len(self.evidence_summary),
            "contradictions": [c.to_dict() for c in self.contradictions],
            "missing_evidence": [m.to_dict() for m in self.missing_evidence],
            "uncertainty_sources": self.uncertainty_sources,
            "alternative_hypotheses": self.alternative_hypotheses,
            "reasoning_graph": self.reasoning_graph.to_dict() if self.reasoning_graph else None,
            "reasoning_trace": self.reasoning_trace,
            "human_summary": self.human_summary,
            "technical_summary": self.technical_summary,
            "gui_summary": self.gui_summary.to_dict() if self.gui_summary else None,
            "model_versions": self.model_versions,
            "processing_versions": self.processing_versions,
            "warnings": self.warnings
        }
